name: release

on:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

permissions:
  contents: write
  issues: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment:
      name: pypi
      url: https://pypi.org/p/affixapi

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version-file: python-version

      - name: prepare python-sdk
        run: |
          python3 -m pip install --upgrade build
          python3 -m build

        # wait upto 90s
      - name: pause to avoid 2ndary rate limits # https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#about-secondary-rate-limits
        run: |
          sleep "$(echo $RANDOM % 90 + 1 | bc)"

      - uses: cycjimmy/semantic-release-action@v4.0.0
        with:
          semantic_version: 18
          extra_plugins: |
            @semantic-release/changelog@6.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
